-- 1. Crear tabla si no existe
create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text not null,
  is_active boolean default false,
  background_color text default '#1D1D1F', -- Para personalizar el fondo
  action_text text default 'Ver más',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Agregar columna product_id de manera segura (si no existe)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'banners' and column_name = 'product_id') then
    alter table public.banners add column product_id bigint references public.products(id);
  end if;
end $$;

-- 3. Habilitar RLS (seguro de re-ejecutar)
alter table public.banners enable row level security;

-- 4. Re-crear Políticas de Seguridad (Elimina las anteriores para evitar errores de duplicado)
drop policy if exists "Banners are viewable by everyone" on public.banners;
create policy "Banners are viewable by everyone" 
  on public.banners for select 
  using (true);

drop policy if exists "Admins can manage banners" on public.banners;
create policy "Admins can manage banners" 
  on public.banners for all 
  using (auth.role() = 'authenticated');
