-- Habilitar extensión UUID
create extension if not exists "uuid-ossp";

-- 1. ENUMS (Enumeraciones) - Usamos DO blocks para evitar errores si ya existen
do $$ begin
    create type user_role as enum ('administrador', 'cajero', 'cocina');
exception
    when duplicate_object then null;
end $$;

do $$ begin
    create type order_status as enum ('pendiente', 'procesando', 'completado', 'cancelado');
exception
    when duplicate_object then null;
end $$;

-- 2. USUARIOS (Extiende auth.users)
create table if not exists public.usuarios (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  role user_role default 'cajero',
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar seguridad a nivel de fila (RLS)
alter table public.usuarios enable row level security;

-- Políticas (usamos DO block oDROP IF EXISTS para recrear es más limpio, pero IF NOT EXISTS en policies es complejo en SQL puro,
-- así que lo dejaremos simple. Si falla por política existente, el usuario puede ignorarlo o borrarla manual.
-- Para ser más robusto, borramos antes de crear)
drop policy if exists "Perfiles públicos son visibles por todos." on public.usuarios;
create policy "Perfiles públicos son visibles por todos." on public.usuarios for select using (true);

drop policy if exists "Usuarios pueden insertar su propio perfil." on public.usuarios;
create policy "Usuarios pueden insertar su propio perfil." on public.usuarios for insert with check (auth.uid() = id);

drop policy if exists "Usuarios pueden actualizar su propio perfil." on public.usuarios;
create policy "Usuarios pueden actualizar su propio perfil." on public.usuarios for update using (auth.uid() = id);

-- 3. CATEGORIAS
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. PRODUCTOS
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price decimal(10,2) not null,
  imagen_url text, -- URL de la imagen en Supabase Storage
  category_id bigint references public.categories(id),
  available boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. ORDENES (PEDIDOS)
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references public.usuarios(id),
  status order_status default 'pendiente',
  total_amount decimal(10,2) default 0.00,
  tax_amount decimal(10,2) default 0.00,
  payment_method text check (payment_method in ('tarjeta', 'efectivo')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. ITEMS DE ORDEN
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  quantity integer not null default 1,
  unit_price decimal(10,2) not null, -- Precio al momento de la compra
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. CHAT / CONVERSACIONES
create table if not exists public.conversations (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.conversation_participants (
  conversation_id uuid references public.conversations(id) on delete cascade,
  user_id uuid references public.usuarios(id) on delete cascade,
  primary key (conversation_id, user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid references public.conversations(id) on delete cascade,
  sender_id uuid references public.usuarios(id),
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- DATOS DE PRUEBA (Categorías opcionales)
insert into public.categories (name, slug) values
('Pizzas', 'pizzas'),
('Combos', 'combos'),
('Bebidas', 'bebidas'),
('Extras', 'extras')
on conflict (slug) do nothing;

-- Trigger para creación automática de perfil
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.usuarios (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', 'cajero')
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- Recrear el trigger para evitar errores de duplicado
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

