-- MASTER FIX SCRIPT FOR MISSING TABLES AND COLUMNS
-- Run this entire script in your Supabase SQL Editor to fix the "customer_id" error.

BEGIN;

-- 1. Create 'customers' table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add 'customer_id' to 'orders' table if it's missing
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'customer_id') THEN
        ALTER TABLE public.orders ADD COLUMN customer_id BIGINT REFERENCES public.customers(id);
    END IF;
END $$;

-- 3. Enable Security (RLS) for customers
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies for customers (if they don't exist)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'customers' AND policyname = 'Enable read/write for authenticated users') THEN
        CREATE POLICY "Enable read/write for authenticated users" ON public.customers FOR ALL USING (auth.role() = 'authenticated');
    END IF;
END $$;

-- 5. Grant permissions
GRANT ALL ON public.customers TO authenticated;
GRANT ALL ON public.customers TO service_role;

COMMIT;
