-- Create chat_messages table
create table if not exists chat_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  customer_name text, -- Store name for easier display on admin side
  sender text check (sender in ('client', 'admin')) not null,
  message text not null,
  is_read boolean default false
);

-- Enable RLS
alter table chat_messages enable row level security;

-- Policies
-- 1. Users can see their own messages
create policy "Users can translate their own messages"
  on chat_messages for select
  using (auth.uid() = user_id);

-- 2. Users can insert their own messages (as client)
create policy "Users can send messages"
  on chat_messages for insert
  with check (auth.uid() = user_id);

-- 3. Grant access to service role/admins (Adjust based on your auth setup)
-- For this simplified prototype, we might need a way for the 'admin' to read all.
-- If you have a specific admin role in public.users:
-- create policy "Admins can view all" on chat_messages for all using (exists (select 1 from users where id = auth.uid() and role = 'admin'));

-- For now, allow public read/write if easy dev mode is needed, OR 
-- simply create a View for admins or rely on the fact that existing 'OrdersView' components usually run with high privileges or specific RLS.
-- Let's stick to standard RLS for safety: Users see theirs.
-- We will assume the Admin Page uses a Supabase client with privileges or the user viewing it is an admin.
