-- Create chat_messages table
create table if not exists chat_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  customer_name text, -- Store name for easier display on admin side
  sender text check (sender in ('client', 'admin')) not null,
  message text not null,
  is_read boolean default false
);

-- Enable RLS
alter table chat_messages enable row level security;

-- Policies

-- 1. Users can see their own messages
create policy "Users can see their own messages"
  on chat_messages for select
  using (auth.uid() = user_id);

-- 2. Users can insert their own messages (as client)
create policy "Users can send messages"
  on chat_messages for insert
  with check (auth.uid() = user_id);

-- 3. Admins and Cajeros can view ALL messages
create policy "Admins View All"
  on chat_messages for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.role in ('administrador', 'cajero')
    )
  );

-- 4. Admins and Cajeros can reply (insert)
create policy "Admins Reply"
  on chat_messages for insert
  with check (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.role in ('administrador', 'cajero')
    )
  );

-- 5. Admins and Cajeros can update (mark as read)
create policy "Admins Update"
  on chat_messages for update
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.role in ('administrador', 'cajero')
    )
  );
