-- Create roles table
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default roles if they don't exist
INSERT INTO roles (name, description)
VALUES 
    ('administrador', 'Acceso total al sistema'),
    ('cajero', 'Acceso a punto de venta y gestión de órdenes'),
    ('cocina', 'Acceso a visualización de órdenes pendientes'),
    ('cliente', 'Acceso limitado a perfil y pedidos personales')
ON CONFLICT (name) DO NOTHING;

-- Enable RLS
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable read access for all users" ON roles
    FOR SELECT USING (true);

CREATE POLICY "Enable write access for admins only" ON roles
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
            AND profiles.role = 'administrador'
        )
    );
